#!/usr/bin/env sh

brew install \
    wget \
    awscli \
    neovim \
    python@3.11 \
    pyenv \
    direnv \
    jq \
    fzf \
    k9s \
    kubectx \
    pre-commit \
    tree \
    java \
    pinentry-mac

brew tap hashicorp/tap
brew install hashicorp/tap/terraform

mkdir ~/.fonts
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
echo "Font settings must be configured in the client terminal."

brew install romkatv/powerlevel10k/powerlevel10k
echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc

