#!/usr/bin/env sh


brew install \
    apache-spark \
    awscli \
    bufbuild/buf/buf \
    direnv \
    fzf \
    java \
    jq \
    k9s \
    kubectx \
    neovim \
    openjdk@11 \
    pinentry-mac \
    pipx \
    pre-commit \
    protolint \
    pyenv \
    python@3.11 \
    ruff \
    shellcheck \
    terraform-docs \
    tree \
    wget \
    yamllint

pipx ensurepath

brew tap hashicorp/tap
brew install hashicorp/tap/terraform
brew install hashicorp/tap/vault

brew tap databricks/tap
brew install databricks

brew install --cask rancher


# optional: terminal & font customization
mkdir ~/.fonts
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
wget -P ~/.fonts https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
echo "Font settings must be configured in the client terminal."

brew install romkatv/powerlevel10k/powerlevel10k
echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc

