#!/usr/bin/env sh

PROJECT_ROOT=$(git rev-parse --show-toplevel)

# git
ln -sf $PROJECT_ROOT/git/config ~/.gitconfig
ln -sf $PROJECT_ROOT/git/ignore ~/.gitignore

# shell
ln -sf $PROJECT_ROOT/.zshrc ~/.zshrc
ln -sf $PROJECT_ROOT/.aliases ~/.aliases
ln -sf $PROJECT_ROOT/.secrets ~/.secrets

