#!/usr/bin/env sh

PROJECT_ROOT=$(git rev-parse --show-toplevel)

# global
touch ~/.secrets


# git
ln $PROJECT_ROOT/git/config ~/.gitconfig
ln $PROJECT_ROOT/git/ignore ~/.gitignore 

# shell
echo "Moving .zshrc to .zshrc_backup. Linking VCS config to ~/.zshrc"
mv ~/.zshrc ~/.zshrc_backup
ln $PROJECT_ROOT/.zshrc ~/.zshrc
ln $PROJECT_ROOT/.aliases ~/.aliases

ln $PROJECT_ROOT/powerlevel10k.zsh-theme $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme